pipeline{
    agent{
        label "physical"
    }
    stages{
        stage('Checkout'){
            steps{
                checkout scm
            }
        }

        stage('Build'){
            steps{
                dir('frontend'){
                    script{
                        sh 'npm install'
                        sh 'vite build'
                    }
                }
            }
        }

        // Assuming swa npm package is installed globally
        stage('Deploy'){
            steps{
                dir('frontend'){
                    script{
                        sh 'npx swa deploy --env production'
                    }
                }
            }
        }
    }
}