pipeline{
    agent{
        label "physical"
    }
    stages{
        stage('Checkout'){
            steps{
                checkout scm
            }
        }

        // Assuming swa npm package is installed globally
        stage('Deploy'){
            steps{
                script{
                    sh 'npx swa deploy --env production'
                }
            }
        }
    }
}