FROM node:22-alpine
WORKDIR /build

RUN npm install prisma uuid
COPY . .

ENTRYPOINT ["sh", "-c", \
    "mkdir -p migrations/0_init \
    && npx prisma migrate diff \
    --from-empty \
    --to-schema-datamodel schema.prisma \
    --script > migrations/0_init/migration.sql \
    && npx prisma migrate reset --force --skip-generator --skip-seed \
    && npx prisma migrate deploy \
    && npx prisma generate --generator client \
    && node seed.js"]