pipeline{
    agent{
        label "physical"
    }

    environment{
        DOCKER_REGISTRY = "docker.io/kng1259"
        DOCKER_CREDENTIALS_ID = "dockerhub-credentials"
        IMAGE_TAG = "0.0.1"
    }

    stages{
        stage('Checkout'){
            steps{
                checkout scm
            }
        }

        // Using docker plugin
        stage('Build'){
            steps{
                dir('backend'){
                    script{
                        def dockerImage = docker.build("${DOCKER_REGISTRY}/backend:${IMAGE_TAG}")
                    }
                }
                dir('backend/prisma'){
                    script{
                        def dockerInitImage = docker.build("${DOCKER_REGISTRY}/backend-init:${IMAGE_TAG}", "-f Dockerfile.init .")
                    }
                }
            }
        }

        stage('Push to Registry'){
            steps{
                script{
                    docker.withRegistry("https://${DOCKER_REGISTRY}", DOCKER_CREDENTIAL_ID){ 
                        dockerImage.push()
                        dockerInitImage.push()
                    }
                }
            }
        }
    }
}