pipeline{
    agent{
        label "physical"
    }

    environment{
        DOCKER_REGISTRY = "docker.io/kng1259"
        DOCKER_CREDENTIALS_ID = "dockerhub-credentials"
        IMAGE_TAG = "0.0.1"
    }

    stages{
        stage('Checkout'){
            steps{
                checkout scm
            }
        }

        // Using docker plugin
        stage('Build'){
            steps{
                dir('backend'){
                    script{
                        dockerImage = docker.build("${DOCKER_REGISTRY}/iot-backend:${IMAGE_TAG}")
                    }
                }
                dir('backend/prisma'){
                    script{
                        dockerInitImage = docker.build("${DOCKER_REGISTRY}/iot-backend-init:${IMAGE_TAG}", "-f Dockerfile.init .")
                    }
                }
            }
        }

        stage('Push to Registry'){
            steps{
                script{
                    docker.withRegistry("https://${DOCKER_REGISTRY}", DOCKER_CREDENTIALS_ID){ 
                        try{
                            dockerImage.push()
                            dockerInitImage.push()
                        }catch(Exception e){
                            error "Failed to push to registry: ${e}"
                        }
                    }
                }
            }
        }
    }
}