services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - mqtt

  adapter:
    build: .
    container_name: adapter
    ports:
      - "8883:8883"
    depends_on:
      - mosquitto
    environment:
      - MQTT_HOST=mosquitto
    networks:
      - mqtt

networks:
  mqtt:
    driver: bridge
